/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosistemacomprasonline;

import classes.InterfacePedidosRemote;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import entidade.Produtos;
import classes.InterfaceProdutosRemote;
import classes.InterfaceVendasRemote;
import entidade.Pedidos;
import entidade.Vendas;
import java.awt.List;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class ProjetoCompras extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoCompras
     */
    public ProjetoCompras() {
        initComponents();
        centralizar();
        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jtablePedidos1 = new javax.swing.JTable();
        Projeto = new javax.swing.JTabbedPane();
        Vendas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdiav = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        txtProduto1 = new javax.swing.JTextField();
        txtPreco1 = new javax.swing.JTextField();
        txtQuant1 = new javax.swing.JTextField();
        txtValor1 = new javax.swing.JTextField();
        txtID2 = new javax.swing.JTextField();
        txtID3 = new javax.swing.JTextField();
        txtProduto2 = new javax.swing.JTextField();
        txtProduto3 = new javax.swing.JTextField();
        txtPreco2 = new javax.swing.JTextField();
        txtPreco3 = new javax.swing.JTextField();
        txtQuant2 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        txtQuant3 = new javax.swing.JTextField();
        txtValor3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jbCartao = new javax.swing.JButton();
        jbDinheiro = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();
        jbCadastrarVendas = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtmesv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtanov = new javax.swing.JTextField();
        Relatorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtquant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        jbRelatorio = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        Pedidos = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jbPedidos = new javax.swing.JButton();
        txtIDPedido = new javax.swing.JTextField();
        jcStatus = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablePedidos = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtStatusAtual = new javax.swing.JTextField();
        jbAlterarPedidos = new javax.swing.JButton();
        Estoque = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jbRecebimento = new javax.swing.JButton();
        jbQuant = new javax.swing.JButton();
        Logoff = new javax.swing.JPanel();
        jbLogoff = new javax.swing.JButton();
        jcFilial = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jtablePedidos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vendas de Balcão");

        jLabel7.setText("Dia");

        txtdiav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiavActionPerformed(evt);
            }
        });

        jLabel9.setText("ID");

        jLabel10.setText("Produto");

        jLabel11.setText("Preço");

        jLabel12.setText("Quant.");

        jLabel13.setText("Valor");

        jLabel14.setText("TOTAL");

        jLabel15.setText("Formas de Pagamento");

        jbCartao.setText("Cartão");
        jbCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCartaoActionPerformed(evt);
            }
        });

        jbDinheiro.setText("Dinheiro");
        jbDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDinheiroActionPerformed(evt);
            }
        });

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jbCadastrarVendas.setText("Finalizar");
        jbCadastrarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarVendasActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Mes");

        jLabel3.setText("Ano");

        javax.swing.GroupLayout VendasLayout = new javax.swing.GroupLayout(Vendas);
        Vendas.setLayout(VendasLayout);
        VendasLayout.setHorizontalGroup(
            VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdiav, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmesv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel13)
                        .addGap(37, 37, 37))
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtanov, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(VendasLayout.createSequentialGroup()
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtID3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VendasLayout.createSequentialGroup()
                                .addComponent(jbCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jbDinheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE))
                            .addGroup(VendasLayout.createSequentialGroup()
                                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtProduto3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txtProduto1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProduto2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPreco1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(txtPreco2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(txtPreco3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendasLayout.createSequentialGroup()
                                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuant3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuant1)
                                        .addComponent(txtQuant2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(txtValor1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValor3)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jbCadastrarVendas, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCalcular))
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VendasLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel6))
                            .addGroup(VendasLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel15)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VendasLayout.setVerticalGroup(
            VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdiav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtmesv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtanov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VendasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jbCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(2, 2, 2)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCartao)
                    .addComponent(jbDinheiro)
                    .addComponent(jbCadastrarVendas)))
        );

        Projeto.addTab("Vendas", Vendas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Relatório de Fechamento de Vendas Diárias");

        jLabel4.setText("Quantidade Produtos Vendidos");

        jLabel5.setText("R$");

        jbRelatorio.setText("Relatorio");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jbLimpar.setText("Cancelar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jLabel21.setText("Dia");

        jLabel22.setText("Mes");

        jLabel8.setText("Ano");

        javax.swing.GroupLayout RelatorioLayout = new javax.swing.GroupLayout(Relatorio);
        Relatorio.setLayout(RelatorioLayout);
        RelatorioLayout.setHorizontalGroup(
            RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RelatorioLayout.createSequentialGroup()
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RelatorioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbLimpar)
                        .addGap(71, 71, 71)
                        .addComponent(jbRelatorio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RelatorioLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(RelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
            .addGroup(RelatorioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RelatorioLayout.setVerticalGroup(
            RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRelatorio)
                    .addComponent(jbLimpar))
                .addContainerGap())
        );

        Projeto.addTab("Relatório", Relatorio);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Pedidos");

        jLabel18.setText("Alterar Status do Pedido");

        jLabel19.setText("ID Pedido");

        jLabel20.setText("Novo Status ");

        jbPedidos.setText("OK");
        jbPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidosActionPerformed(evt);
            }
        });

        jcStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AGUARDANDO APROVAÇÃO", "APROVADO", "REPROVADO", "TRANSPORTADORA", "ENTREGUE" }));
        jcStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcStatusActionPerformed(evt);
            }
        });

        jtablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID PEDIDO", "DATA", "ID USUARIO", "ID PRODUTO", "QUANTIDADE", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(jtablePedidos);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jLabel23.setText("Status Atual");

        jbAlterarPedidos.setText("Alterar");
        jbAlterarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PedidosLayout = new javax.swing.GroupLayout(Pedidos);
        Pedidos.setLayout(PedidosLayout);
        PedidosLayout.setHorizontalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidosLayout.createSequentialGroup()
                        .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PedidosLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18))
                                    .addGroup(PedidosLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(31, 31, 31)))
                                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStatusAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PedidosLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PedidosLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel17)
                .addGap(178, 178, 178)
                .addComponent(jbAtualizar)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(PedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarPedidos)
                .addGap(29, 29, 29))
        );
        PedidosLayout.setVerticalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jbAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(1, 1, 1)
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIDPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPedidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtStatusAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterarPedidos)
                .addContainerGap())
        );

        Projeto.addTab("Pedidos", Pedidos);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Selecione a opção");

        jbRecebimento.setText("Recebimento de Produto");
        jbRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRecebimentoActionPerformed(evt);
            }
        });

        jbQuant.setText("Quantidade de Produto");
        jbQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstoqueLayout = new javax.swing.GroupLayout(Estoque);
        Estoque.setLayout(EstoqueLayout);
        EstoqueLayout.setHorizontalGroup(
            EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstoqueLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel16)
                .addGap(0, 216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstoqueLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRecebimento, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        EstoqueLayout.setVerticalGroup(
            EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(57, 57, 57)
                .addComponent(jbRecebimento)
                .addGap(60, 60, 60)
                .addComponent(jbQuant)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Projeto.addTab("Estoque", Estoque);

        jbLogoff.setText("Fazer Logoff");
        jbLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogoffLayout = new javax.swing.GroupLayout(Logoff);
        Logoff.setLayout(LogoffLayout);
        LogoffLayout.setHorizontalGroup(
            LogoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoffLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jbLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        LogoffLayout.setVerticalGroup(
            LogoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoffLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jbLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        Projeto.addTab("Logoff", Logoff);

        jcFilial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "FILIAL1", "FILIAL2" }));

        jLabel24.setText("Filial");

        jLabel25.setText("FILIAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Projeto))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(40, 40, 40)
                .addComponent(jcFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(269, 269, 269)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Projeto)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addComponent(jLabel24)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRecebimentoActionPerformed
        // TODO add your handling code here:
         RecebimentoProduto re = new RecebimentoProduto();
         re.setVisible(true);
         dispose();
        
        
    }//GEN-LAST:event_jbRecebimentoActionPerformed

    private void jcStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcStatusActionPerformed

    private void jbPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidosActionPerformed
        // TODO add your handling code here;:
         ;
         InitialContext ctx;
         Pedidos ped= new Pedidos();
         ped.setId(Long.parseLong(txtIDPedido.getText()));
         ped.setFilialentrega(String.valueOf(jcFilial.getSelectedItem()));
            try {
            ctx = new InitialContext();

            
            InterfacePedidosRemote pedidorem = (InterfacePedidosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClassePedidoRe");
            ped= pedidorem.consultarPedidosFilial(ped);
            
            if(ped!=null){
                txtStatusAtual.setText(String.valueOf(ped.getStatus()));
                
               
            }
            
            else{
                 JOptionPane.showMessageDialog(this, "Pedido não existe");
            }
            }catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(ProjetoCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jbPedidosActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        // TODO add your handling code here:
        
        Vendas ven = new Vendas();
        
        Vendas ventemp = new Vendas();
        
        
        int dia;
        dia = Integer.parseInt(txtDia.getText());
        int mes = Integer.parseInt(txtMes.getText());
        int ano = Integer.parseInt(txtAno.getText());
        InitialContext ctx;

        ven.setDia(dia);
        ven.setMes(mes);
        ven.setAno(ano);
            try {
                ctx = new InitialContext();

                InterfaceVendasRemote venrem = (InterfaceVendasRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClasseVendas");

               
                
             
                
                ventemp = venrem.consultarVendas(ven);


                if (ventemp != null) {
                    

                    txtquant.setText(String.valueOf(ventemp.getQuant()));
                    txtvalor.setText(String.valueOf(ventemp.getValor()));
                } else {
                                       
                    
                    JOptionPane.showMessageDialog(this, "Para esta data não houve vendas");
                   
                }
            } catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        
                    ProjetoCompras proj = new ProjetoCompras();
                    proj.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogoffActionPerformed
        // TODO add your handling code here:
        
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbLogoffActionPerformed

    private void jbQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuantActionPerformed
        // TODO add your handling code here:
        QuantidadeProduto quan = new QuantidadeProduto();
        quan.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jbQuantActionPerformed

    private void jbCadastrarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarVendasActionPerformed
        // TODO add your handling code here:
        Vendas ven = new Vendas();
        Vendas ven2 = new Vendas();
        
         int dia;
        dia = Integer.parseInt(txtdiav.getText());
        int mes = Integer.parseInt(txtmesv.getText());
        int ano = Integer.parseInt(txtanov.getText());
        InitialContext ctx;
        
        try {
            ctx = new InitialContext();

            InterfaceVendasRemote venrem = (InterfaceVendasRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClasseVendas");
           
            
            ven.setDia(dia);
            ven.setMes(mes);
            ven.setAno(ano);
            ven.setQuant(Integer.parseInt(txtQuant1.getText())+ Integer.parseInt(txtQuant2.getText())+ Integer.parseInt(txtQuant3.getText()));
            ven.setValor(Double.parseDouble(txtValorTotal.getText()));

            if (venrem.consultarVendas(ven) == null) {
                venrem.incluir(ven);

                JOptionPane.showMessageDialog(this, "Venda Cadastrada com Sucesso");
                ProjetoCompras proj = new ProjetoCompras();
                proj.setVisible(true);
                dispose();
            } else {
                ven2= venrem.consultarVendas(ven);
                int quanttemp= ven2.getQuant()+ven.getQuant();
                double valortemp = ven2.getValor()+ven.getValor();
                ven2.setQuant(quanttemp);
                ven2.setValor(valortemp);
                venrem.alterar(ven2);

                JOptionPane.showMessageDialog(this, "Venda Cadastrada com Sucesso");

                ProjetoCompras proj = new ProjetoCompras();
                proj.setVisible(true);
                dispose();
            }
        } catch (NamingException ex) {
            System.out.println("Erro de Transação");
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbCadastrarVendasActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        
          InitialContext ctx;
          Produtos prod = new Produtos();
           
          

                try {
                ctx = new InitialContext();

                InterfaceProdutosRemote prodrem = (InterfaceProdutosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClasseProdutoRe");

                prod.setId(Long.parseLong(txtID1.getText()));
                int quant1= (Integer.parseInt(txtQuant1.getText()));
                prod = prodrem.consultar(prod);
                
                if(String.valueOf(jcFilial.getSelectedItem()).equals("FILIAL1")){
                  if(prod.getEstoque1()>= quant1){
                    int temp= prod.getEstoque1()-quant1;
                    prod.setEstoque1(temp);
                    prodrem.alterar(prod);
                       
                }
                else{
                   txtQuant1.setText(""+prod.getEstoque1());
                   prod.setEstoque1(0);
                   prodrem.alterar(prod);
                   
                    
                }
                  
                  
                
                int quant2= (Integer.parseInt(txtQuant2.getText()));
                prod = prodrem.consultar(prod);
                
                if(prod.getEstoque1()>= quant2){
                    int temp= prod.getEstoque1()-quant2;
                    prod.setEstoque1(temp);
                    prodrem.alterar(prod);
                       
                }
                else{
                   txtQuant2.setText(""+prod.getEstoque1());
                   prod.setEstoque1(0);
                   prodrem.alterar(prod);
                   
                    
                }
                int quant3= (Integer.parseInt(txtQuant3.getText()));
                prod = prodrem.consultar(prod);
                
                if(prod.getEstoque1()>=quant3){
                    int temp= prod.getEstoque1()-quant3;
                    prod.setEstoque1(temp);
                    prodrem.alterar(prod);
                     
                }
                else{
                  
                   txtQuant3.setText(""+prod.getEstoque1()); 
                   prod.setEstoque1(0);
                   prodrem.alterar(prod);
                   
                    
                }
                }
                else{
                    if(prod.getEstoque2()>= quant1){
                    int temp= prod.getEstoque2()-quant1;
                    prod.setEstoque2(temp);
                    prodrem.alterar(prod);
                       
                }
                else{
                   txtQuant1.setText(""+prod.getEstoque2());
                   prod.setEstoque2(0);
                   prodrem.alterar(prod);
                   
                    
                }
                  
                  
                
                int quant2= (Integer.parseInt(txtQuant2.getText()));
                prod = prodrem.consultar(prod);
                
                if(prod.getEstoque2()>= quant2){
                    int temp= prod.getEstoque2()-quant2;
                    prod.setEstoque2(temp);
                    prodrem.alterar(prod);
                       
                }
                else{
                   txtQuant2.setText(""+prod.getEstoque2());
                   prod.setEstoque2(0);
                   prodrem.alterar(prod);
                   
                    
                }
                int quant3= (Integer.parseInt(txtQuant3.getText()));
                prod = prodrem.consultar(prod);
                
                if(prod.getEstoque2()>=quant3){
                    int temp= prod.getEstoque2()-quant3;
                    prod.setEstoque2(temp);
                    prodrem.alterar(prod);
                     
                }
                else{
                  
                   txtQuant3.setText(""+prod.getEstoque1()); 
                   prod.setEstoque2(0);
                   prodrem.alterar(prod);
                   
                    
                }
                
                }
                }catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(ProjetoCompras.class.getName()).log(Level.SEVERE, null, ex);
            }          
        
        
        
        
        double valortotal1= Double.parseDouble(txtPreco1.getText())* Double.parseDouble(txtQuant1.getText());
                txtValor1.setText(String.valueOf(valortotal1));
                double valortotal2= Double.parseDouble(txtPreco2.getText())* Double.parseDouble(txtQuant2.getText());
                txtValor2.setText(String.valueOf(valortotal2));
                double valortotal3= Double.parseDouble(txtPreco3.getText())* Double.parseDouble(txtQuant3.getText());
                txtValor3.setText(String.valueOf(valortotal3));
                
                
                double valoracumulado= valortotal1 + valortotal2 + valortotal3;
                txtValorTotal.setText(String.valueOf(valoracumulado));
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDinheiroActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "Dinheiro recebido com sucesso");
    }//GEN-LAST:event_jbDinheiroActionPerformed

    private void jbCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCartaoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Insira o cartão");
    }//GEN-LAST:event_jbCartaoActionPerformed

    private void txtdiavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiavActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
       Produtos prod = new Produtos();
        InitialContext ctx;

                   try {
                ctx = new InitialContext();

                InterfaceProdutosRemote prodrem = (InterfaceProdutosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClasseProdutoRe");

                prod.setId(Long.parseLong(txtID1.getText()));
                prod = prodrem.consultar(prod);
                if (prod!= null) {
                    txtProduto1.setText(prod.getDescricao());
                    txtPreco1.setText(prod.getPreco());
                } else {
                   txtProduto1.setText("");
                   txtPreco1.setText("0");
                }
                
                if(txtID2.getText().trim().equals("")){
                   txtProduto2.setText("");
                   txtPreco2.setText("0");
                   txtQuant2.setText("0");
                }
                
                
                else{
                prod.setId(Long.parseLong(txtID2.getText()));
                
                


                prod = prodrem.consultar(prod);
                if (prod!= null) {
                    txtProduto2.setText(prod.getDescricao());
                    txtPreco2.setText(prod.getPreco());
                } else {
                   txtProduto2.setText("");
                   txtPreco2.setText("0");
                   txtQuant2.setText("0");
                }
                
                }
                 if(txtID3.getText().trim().equals("")){
                   txtProduto3.setText("");
                   txtPreco3.setText("0");
                   txtQuant3.setText("0");
                }
                
                
                else{
                
                prod.setId(Long.parseLong(txtID3.getText()));
                
                prod = prodrem.consultar(prod);
                if (prod!= null) {
                    txtProduto3.setText(prod.getDescricao());
                    txtPreco3.setText(prod.getPreco());
                } else {
                    txtProduto3.setText("");
                    txtPreco3.setText("0");
                    txtQuant2.setText("0");
                }
                 }
                   }catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(ProjetoCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
    
         
        
        
        
        
        
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        Pedidos ped= new Pedidos();
        ped.setFilialentrega(String.valueOf(jcFilial.getSelectedItem()));
        InitialContext ctx;
        long i=1;
        DefaultTableModel modelo = (DefaultTableModel) jtablePedidos.getModel();
        modelo.setNumRows(0);
        
                try {
                ctx = new InitialContext();

                InterfacePedidosRemote pedidorem = (InterfacePedidosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClassePedidoRe");
                ped.setId(i);
                ped = pedidorem.consultarPedidosFilial(ped);
                while(ped != null){
                
                
                
                Object[] row = {String.valueOf(ped.getId()), String.valueOf(ped.getData()), String.valueOf(ped.getIdUsuario()),String.valueOf(ped.getIdProduto()),
                String.valueOf(ped.getQuantidade()),String.valueOf(ped.getStatus()) };
                modelo.addRow(row);
                i++;
                ped.setId(i);
                ped = pedidorem.consultarPedidos(ped);
                
                }
               
                }catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(ProjetoCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
       
       
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbAlterarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPedidosActionPerformed
        // TODO add your handling code here:
        
         InitialContext ctx;
         Pedidos ped= new Pedidos();
         ped.setId(Long.parseLong(txtIDPedido.getText()));
         ped.setFilialentrega(String.valueOf(jcFilial.getSelectedItem()));

            try {
            ctx = new InitialContext();

            
            InterfacePedidosRemote pedidorem = (InterfacePedidosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClassePedidoRe");
            ped= pedidorem.consultarPedidosFilial(ped);
            
            if(ped!=null){
                
                if(jcStatus.getSelectedItem().equals("ENTREGUE"))
                    {
                    
                    Produtos prod = new Produtos();
                    InterfaceProdutosRemote prodrem = (InterfaceProdutosRemote) ctx.lookup("java:global/ProjetoSistemaComprasOnline/ProjetoSistemaComprasOnline-ejb/ClasseProdutoRe");

                    prod.setId(Long.parseLong(ped.getIdProduto()));
                    int quant1= ped.getQuantidade();
                    prod = prodrem.consultar(prod);
                    if(ped.getFilialentrega().equals("FILIAL1")){
                    if(prod.getEstoque1()>= quant1){
                       int temp= prod.getEstoque1()-quant1;
                       prod.setEstoque1(temp);
                       prodrem.alterar(prod);
                       ped.setStatus((String.valueOf(jcStatus.getSelectedItem())));
                       pedidorem.alterar(ped);
                       JOptionPane.showMessageDialog(this, "Alterado com sucesso!!");
                       txtIDPedido.setText("");
                       txtStatusAtual.setText("");
                       jcStatus.setSelectedItem("Selecione");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Quantidade insuficiente no estoque!!");
                        txtIDPedido.setText("");
                       txtStatusAtual.setText("");
                    }

                    }
                    else{
                        int temp= prod.getEstoque2()-quant1;
                       prod.setEstoque2(temp);
                       prodrem.alterar(prod);
                       ped.setStatus((String.valueOf(jcStatus.getSelectedItem())));
                       pedidorem.alterar(ped);
                       JOptionPane.showMessageDialog(this, "Alterado com sucesso!!");
                       txtIDPedido.setText("");
                       txtStatusAtual.setText("");
                       jcStatus.setSelectedItem("Selecione");
                    }
                    
                    }
                else{
                    ped.setStatus((String.valueOf(jcStatus.getSelectedItem())));
                    pedidorem.alterar(ped);
                    JOptionPane.showMessageDialog(this, "Alterado com sucesso!!");
                    txtIDPedido.setText("");
                    txtStatusAtual.setText("");
                    jcStatus.setSelectedItem("Selecione");
                }
               
            }
            
            else{
                 JOptionPane.showMessageDialog(this, "Pedido não existe");
            }
            }catch (NamingException ex) {
                System.out.println("Erro de Transação");
                Logger.getLogger(ProjetoCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jbAlterarPedidosActionPerformed

    
                                             
        

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoCompras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Estoque;
    private javax.swing.JPanel Logoff;
    private javax.swing.JPanel Pedidos;
    private javax.swing.JTabbedPane Projeto;
    private javax.swing.JPanel Relatorio;
    private javax.swing.JPanel Vendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton jbAlterarPedidos;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCadastrarVendas;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbCartao;
    private javax.swing.JButton jbDinheiro;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLogoff;
    private javax.swing.JButton jbPedidos;
    private javax.swing.JButton jbQuant;
    private javax.swing.JButton jbRecebimento;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JComboBox jcFilial;
    private javax.swing.JComboBox jcStatus;
    private javax.swing.JTable jtablePedidos;
    private javax.swing.JTable jtablePedidos1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtID3;
    private javax.swing.JTextField txtIDPedido;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPreco1;
    private javax.swing.JTextField txtPreco2;
    private javax.swing.JTextField txtPreco3;
    private javax.swing.JTextField txtProduto1;
    private javax.swing.JTextField txtProduto2;
    private javax.swing.JTextField txtProduto3;
    private javax.swing.JTextField txtQuant1;
    private javax.swing.JTextField txtQuant2;
    private javax.swing.JTextField txtQuant3;
    private javax.swing.JTextField txtStatusAtual;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValor3;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtanov;
    private javax.swing.JTextField txtdiav;
    private javax.swing.JTextField txtmesv;
    private javax.swing.JTextField txtquant;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
   

  private void centralizar() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension janela = getSize();
        if (janela.height > screen.height) {
            setSize(janela.width, screen.height);
        }
        if (janela.width > screen.width) {
            setSize(screen.width, janela.height);
        }
        setLocation((screen.width - janela.width) / 2, (screen.height - janela.height) / 2);


    }
  










}
